---
- name: "Large + 20"
  hosts: clients
  strategy: free
  gather_facts: false
  vars:
    fileserver: "{{ 192.168.178.52:8888 }}"

  tasks:
  - name: "Install curl"
    become: yes
    apt:
      name: curl
      update_cache: yes
      cache_valid_time: 3600

  - import_tasks: get_random.yml

  - name: "Download iso"
    when: inventory_hostname in groups['clients2']
    get_url:
      url: 'http://192.168.178.52:8888/files/Windows.iso?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi
    async: 240
    poll: 0

  - name: "Wait for 2 min"
    when: inventory_hostname in groups['clients1']
    wait_for:
      timeout: 60

  - name: "Download website 20 times"
    when: inventory_hostname in groups['clients1']
    get_url:
      url: 'http://192.168.178.52:8888/files/upload.html?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi
    with_sequence: count=20
...
