---
- name: "50"
  hosts: clients
  strategy: free
  gather_facts: false
  vars:
    fileserver: "{{ 192.168.189.5:8888 }}"

  tasks:
  - name: Create the wifi connection
    community.general.nmcli:
      type: wifi
      conn_name: Projektarbeit
      ifname: wlan0
      ssid: Projektarbeit
      wifi_sec:
        key-mgmt: wpa-psk
        psk: pAssw0rd!
      autoconnect: true
      state: present

  - name: "Install curl"
    become: yes
    apt:
      name: curl
      update_cache: yes
      cache_valid_time: 3600

  - import_tasks: get_random.yml

  - name: "Download video"
    get_url:
      url: 'http://192.168.189.5:8888/files/test.mp4?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi
    async: 240
    poll: 0

  - name: "Download website 50 times"
    get_url:
      url: 'http://192.168.189.5:8888/files/upload.html?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi
    with_sequence: count=50
    async: 240
    poll: 0

  - name: "Upload file"
    shell: 'curl -Ffile=@upload.html "http://192.168.189.5:8888/upload?token=123"'
    with_sequence: count=50
...
