version: '3'
services:
  go-simple-web-server:
      image: mayth/simple-upload-server
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      ports:
      - "192.168.189.5:8888:8888"

      - "192.168.178.40:8888:8888"
      volumes:
      - ./:/home/projektarbeit
      working_dir: /home/projektarbeit
      command: -port 8888 -token 123 -upload_limit 100000000 /home/projektarbeit

  ansible-controller:
      image: willhallonline/ansible:2.11-ubuntu-20.04
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
      - ./:/ansible
      - ./.ssh/id_rsa:/root/.ssh/id_rsa
      environment:
        - "ANSIBLE_HOST_KEY_CHECKING=false"
      working_dir: /ansible
      entrypoint: /bin/bash

  monitor:
    image: inzania/network-traffic-metrics:latest
    network_mode: host
    environment:
      - "NTM_INTERFACE=projektarbeit_default"
      - "NTM_FILTERS=$NTM_FILTERS"

  prometheus:
    image: prom/prometheus:main
    ports:
      - 9090:9090
    volumes:
      - ./network-traffic-metrics/prometheus/:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - "monitor:192.168.189.5"

  grafana:
    image: grafana/grafana:6.6.2
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./network-traffic-metrics/grafana/provisioning:/etc/grafana/provisioning
    links:
      - "prometheus:prometheus"
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"

volumes:
  prometheus-data:
  grafana-data:
