---
- name: "install go"
  hosts: localhost
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"

  tasks:

    - name: "Install go"
      become: yes
      apt:
        name: golang-go

    - name: "verify"
      shell: 'go version'

    - name: "add go path"
      shell: "export GOPATH=$HOME/{{ ansible_user_id }}/go"

    - name: "Add another bin dir to system-wide $PATH."
      become: yes
      copy:
        dest: /etc/profile.d/custom-path.sh
        content: 'PATH=$PATH:{{ home_dir }}/go/bin'

    #- name: "install go-server"
    #  shell: 'go install github.com/mayth/go-simple-upload-server'
    #  environment:
    #    GO111MODULE: ture

    - name: Update apt-get repo and cache
      become: yes
      apt:
        update_cache: yes
        state: fixed
        cache_valid_time: 3600
        autoclean: yes
        autoremove: yes

    - name: "upgrade"
      become: yes
      shell: apt-get upgrade -y

    - name: "Download go-server"
      get_url:
        url: https://github.com/mayth/go-simple-upload-server/archive/refs/tags/v1.2.tar.gz
        dest: "{{ home_dir }}"
        mode: 0755
        owner: "{{ ansible_user_id }}"

    - name: "Create a directory if it does not exist"
      ansible.builtin.file:
        path: "{{ home_dir }}/go-simple-upload-server-1.2"
        state: directory
        mode: '0755'

    - name: "Extract repo into home_dir"
      ansible.builtin.unarchive:
        src: "{{ home_dir }}/go-simple-upload-server-1.2.tar.gz"
        dest: "{{ home_dir }}"

    - name: "build"
      shell: go build
      args:
        chdir: "{{ home_dir }}/go-simple-upload-server-1.2"

    - name: "move file"
      become: yes
      copy:
        src: "{{ home_dir }}/go-simple-upload-server-1.2/go-simple-upload-server"
        dest: /usr/local/bin

    - name: "move .service file"
      become: yes
      copy:
        src: gosimplefileserver.service
        dest: /etc/systemd/system/

    - name: "enable and start service file"
      become: yes
      systemd:
        enabled: yes
        state: started
        name: gosimplefileserver.service
...
