---
- name: "Simulate web traffic"
  hosts: clients
  strategy: free
  gather_facts: false
  vars:
    fileserver: "{{ 192.168.178.52:8888 }}"

  tasks:
  - name: "Install curl"
    become: yes
    apt:
      name: curl
      update_cache: yes
      cache_valid_time: 3600

  - import_tasks: get_random.yml

  - name: "Download index"
    get_url:
      url: 'http://{{ fileserver }}/files/upload.html?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi

  - import_tasks: get_random.yml

  - name: "Download video"
    get_url:
      url: 'http://{{ fileserver }}/files/test.mp4?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi

  - import_tasks: get_random.yml

  - name: "Upload file"
    shell: 'curl -Ffile=@upload.html "http://{{ fileserver }}/upload?token=123"'

  - import_tasks: get_random.yml

  - name: "Download video"
    get_url:
      url: 'http://{{ fileserver }}/files/test.mp4?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi
...
