---
- name: "Simulate web traffic"
  hosts: clients
  strategy: free
  gather_facts: false

  tasks:
  - name: "check if curl is installed"
    shell: 'curl -V'
    register: output

  - name: "Install curl if nessessery"
    import_tasks: install_curl.yml
    when: output is search("The program")

  - import_tasks: get_random.yml

  - name: "Download index"
    get_url:
      url: http://192.168.178.52:8888/files/upload.html?token=123
      dest: /home/pi/
      mode: 0755
      owner: pi

  - import_tasks: get_random.yml

  - name: "Download video"
    get_url:
      url: http://192.168.178.52:8888/files/test.mp4?token=123
      dest: /home/pi/
      mode: 0755
      owner: pi

  - import_tasks: get_random.yml

  - name: "Upload file"
    shell: 'curl -Ffile=@upload.html "http://192.168.178.52:8888/upload?token=123"'

  - import_tasks: get_random.yml

  - name: "Download video"
    get_url:
      url: http://192.168.178.52:8888/files/test.mp4?token=123
      dest: /home/pi/
      mode: 0755
      owner: pi
...