---
- name: "Simulate web traffic"
  hosts: clients
  strategy: free
  gather_facts: false
  vars:
    fileserver: "{{ 192.168.178.32:8888 }}"
    home_dir: "{{ lookup('env', 'HOME') }}"

  tasks:
  - name: "debug home"
    debug:
      msg: "{{ home_dir }}, {{ ansible_user_id }}"

  - name: "Install curl"
    become: yes
    apt:
      name: curl
      update_cache: yes
      cache_valid_time: 3600

  - import_tasks: get_random.yml

  - name: "Download index"
    get_url:
      url: 'http://192.168.178.32:8888/files/upload.html?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi

  - import_tasks: get_random.yml

  - name: "Download video"
    get_url:
      url: 'http://192.168.178.32:8888/files/test.mp4?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi

  - import_tasks: get_random.yml

  - name: "Upload file"
    shell: 'curl -Ffile=@upload.html "http://192.168.178.32:8888/upload?token=123"'

  - import_tasks: get_random.yml

  - name: "Download video"
    get_url:
      url: 'http://192.168.178.32:8888/files/test.mp4?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi
...
