---
- name: "50"
  hosts: all
  strategy: free
  gather_facts: false
  vars:
    fileserver: 192.168.189.5
    logstash: 192.168.178.40

  tasks:

  - name: "Install curl"
    when: inventory_hostname in groups['clients']
    become: yes
    apt:
      name: curl
      update_cache: yes
      cache_valid_time: 3600

  - name: install sar
    when: inventory_hostname in groups['clients']
    become: yes
    apt:
      name: sysstat
      update_cache: yes
      cache_valid_time: 3600

  - name: "start monitroing"
    shell: 'sar -n DEV 1 300 | sed "s/^/`date +"%Y-%m-%d"` {{ inventory_hostname }} /" | nc -q0 {{ logstash }} 5000'
    async: 360
    poll: 0

  - name: "Wait for 2 sec for monitroing"
    wait_for:
      timeout: "2"

  - import_tasks: get_random.yml

  - name: "Download video"
    when: inventory_hostname in groups['clients']
    get_url:
      url: 'http://{{ fileserver }}:8888/files/test.mp4?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi
    async: 240
    poll: 0

  - name: "Download website 50 times"
    when: inventory_hostname in groups['clients']
    get_url:
      url: 'http://{{ fileserver }}:8888/files/upload.html?token=123'
      dest: /home/pi/
      mode: 0755
      owner: pi
    with_sequence: count=50
    async: 240
    poll: 0

  - name: "Upload file"
    when: inventory_hostname in groups['clients']
    shell: 'curl -Ffile=@upload.html "http://{{ fileserver }}:8888/upload?token=123"'
    with_sequence: count=50
...
