---

- name: "Install curl"
  when: inventory_hostname in groups['clients']
  become: yes
  apt:
    name: curl
    update_cache: yes
    cache_valid_time: 3600

- name: "Install sar"
  when: inventory_hostname in groups['clients']
  become: yes
  apt:
    name: sysstat
    update_cache: yes
    cache_valid_time: 3600